version: '3.1'
services:
  zookeeper:
    image: zookeeper
    container_name: my_zookeeper
    restart: always

  nimbus:
    build: jfr_storm/.
    image: jfr_storm
    container_name: my_nimbus
    command: storm nimbus
    #-c nimbus.task.timeout.secs='13'
    depends_on: 
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  supervisor:
    build: jfr_storm/.
    image: jfr_storm
    container_name: my_supervisor_1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    # test ob dann http://644e5353ce74:8000/api/v1/daemonlog?file=supervisor.log erreichbar
    ports:
     - 8000:8000

  ui:
    image: storm
    container_name: my_ui
    command: storm ui
    depends_on:
      - nimbus
    links:
     - nimbus
#     - supervisor
# - supervisor
    restart: always
    ports: 
     - 8080:8080

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: storm_graphite
    environment:
    - STATSD_INTERFACE=tcp
    ports:
    - 80:80
    - 2003-2004:2003-2004
    - 2023-2024:2023-2024
    - 8125:8125/udp
    #- 8125:8125/udp
    - 8126:8126
    links:
     - nimbus
     - supervisor
    restart: always 

  grafana:
    image: grafana/grafana
    container_name: storm_grafana
    ports:
    - 3000:3000
    links:
    - graphite
    restart: always