version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: my_zookeeper
    restart: always

  nimbus:
    image: storm
    container_name: my_nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  supervisor:
    image: storm
    container_name: my_supervisor_1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

  ui:
    image: storm
    container_name: my_ui
    command: storm ui
    depends_on:
      - nimbus
    links:
     - nimbus
    restart: always
    ports: 
     - 8080:8080

   
