scrape_configs:
- job_name: cadvisor
  scrape_interval: 10s
  dns_sd_configs:
   - names: ['tasks.cadvisor']
     type: 'A'
     port: 8080 #internal port
  # static_configs:
  # - targets:
  #   - cadvisor:8081